### ISSUE TITLE
Issue in exercise 7

### ISSUE THREAD

**Issue by anushabc** [microsoft/MCW-Serverless-architecture#105]
-  In Exercise 6  Task 2 step 7 the branch name appears to be master.  I checked the GitHub repo created in previous steps its created with the master branch.

![image](https://user-images.githubusercontent.com/66515706/146994125-30851c36-5641-44e7-a7e4-34fb86a54d0f.png)

-  In Exercise 6 task 3 step 16 I was not able to see the **Build/Deploy**  logs entry. But I got the message the changes were pushed successfully in the previous step.

**Comment by sadukie** [comment]
@anushabc Did you create this repo from the Lab VM? Or are you running this from outside the Lab VM?

**Comment by anushabc** [comment]
I created it from LabVM

**Comment by anushabc** [comment]
I created it from LabVM

**Comment by sadukie** [comment]
@anushabc I was able to replicate this on my end. I am tracking it down now to see why it's happening.

**Comment by sadukie** [comment]
@anushabc It looks like the command to set the default branch for new git repositories isn't getting picked up properly as part of the initial VM set up.  I have a PR in to change the process a bit.

* Before creating the repository, you should be able to run the command `git config --global init.defaultbranch main` to default all new git repositories created in the LabVM to `main`.  This should take care of that.

**Comment by sadukie** [comment]
@anushabc The PR has been merged. Please let us know if you run into any issues with the new change in `main`.

**Comment by anushabc** [comment]
Sure @sadukie. Thank you for the help.

**Comment by DawnmarieDesJardins** [comment]
Thanks all!  Closing the issue as resolved.

**Comment by Karthikkc123** [comment]
@sadukie In [Exercise-7 Task-1: Run the Logic App Step-3](https://github.com/microsoft/MCW-Serverless-architecture/blob/main/Hands-on%20lab/HOL%20step-by-step%20-%20Serverless%20architecture.md), After running the trigger I'm unable to get expected output in Logic App that **Expression Result as false.**

![image](https://user-images.githubusercontent.com/83394010/147497327-67ed69ae-e132-42c2-951f-ae5ef405ec79.png)

**Comment by DawnmarieDesJardins** [comment]
Reopening for investigation.

**Comment by sadukie** [comment]
@Karthikkc123 I have a PR in to add another Task in Exercise 7.  In order to trigger the ExportLicensePlates function and get a `true` result, you may have to generate more data for it to export the CSV file to storage and end in an OK (status code 200) state.  If it returns `false` and you get a status of 204 (no new plates), check the storage account anyhow for the CSV file. 

The Logic App has no bearing on whether the data goes to storage. It serves the purpose of only notifying you if the function ran and came back with a status code other than 200.

**Comment by DawnmarieDesJardins** [comment]
Closing issue with merge of PR #108

**Comment by Divyasri199** [comment]
Hi @sadukie ,
We have performed the lab, but still we are facing the same issue that the expression results in Logic App is false.

![image](https://user-images.githubusercontent.com/83349577/147575234-f5d9a1bb-11bc-4679-b886-2f9463c56f66.png)

**Note**: We are able to get the expected CSV file in datalake storage account even after getting the expression result as false.

In [Exercise-6/Task-3](https://github.com/microsoft/MCW-Serverless-architecture/blob/main/Hands-on%20lab/HOL%20step-by-step%20-%20Serverless%20architecture.md), after pushing the changes from Visual Studio, we are not able to see the build/deploy logs in the **Deployment Center** of **Tollbooth function**. But we are able to see only the App logs. Please find it in below screenshot for your reference.

![image](https://user-images.githubusercontent.com/83349577/147575756-55c165c7-0c88-41f9-b41e-79a3267acbf1.png)

While exploring the function **exportlicenceplate** in TollBooth function app, under **Monitor**->**Invocation Traces**, we found that 0 license plates are being exported. Please find it from below screenshot for your reference.

![image](https://user-images.githubusercontent.com/83349577/147576570-378c9b38-f8d9-41ce-b993-365525a34d52.png)

**Comment by sadukie** [comment]
@Divyasri199 So some things to note:

* The `false` in [Exercise 7, Task 2](https://github.com/microsoft/MCW-Serverless-architecture/blob/main/Hands-on%20lab/HOL%20step-by-step%20-%20Serverless%20architecture.md#task-2-run-the-logic-app) is going to be a matter of timing.  The data run in [Exercise 7, Task 1](https://github.com/microsoft/MCW-Serverless-architecture/blob/main/Hands-on%20lab/HOL%20step-by-step%20-%20Serverless%20architecture.md#task-1-rerun-upload-images) might be a primer for exporting license plates, but if there's a delay between the Function app processing data and the Logic App being run, then you may not see the `true` response.  Regardless of `true` or `false` in the Logic App, it's the Function app - not the Logic App - that is responsible for putting the CSV file in storage.

* For [Exercise 6, Task 3], it will show **Build/Deploy Logs** if you capture it while running.  If you don't capture it in the Deployment Center while it's running, it will show as **App Logs**.  When I tested it, I didn't see it appear in the Deployment Center right away.  You may need to have both your GitHub Actions and your Deployment Center opened side-by-side so that you can see the GitHub Actions in progress.  Once the GitHub Actions are done, then you should see the entry appear in the Deployment Center.

* As for 0 license plates being exported, you may need to rerun Upload Images, as I added in [Exercise 7, Task 1](https://github.com/microsoft/MCW-Serverless-architecture/blob/main/Hands-on%20lab/HOL%20step-by-step%20-%20Serverless%20architecture.md#task-1-rerun-upload-images) to ensure that license plates are exported.
