### ISSUE TITLE
Activating the visual studio in VM

### ISSUE THREAD

**Issue by PremalathaRajendran1** [microsoft/MCW-Serverless-architecture#112]
[In](![Visual studio](https://user-images.githubusercontent.com/99088477/153105459-128657c8-dda3-42a9-b41b-a7cb12de403b.PNG)) the below link facing issue in Exercise 1: Task 2 step 6. <[Hands-on lab](https://github.com/microsoft/MCW-Serverless-architecture/tree/main/Hands-on%20lab)/HOL step-by-step - Serverless architecture.md>

Task 2: Open the starter solution in Visual Studio

once logged into the visual studio it prompts for the product key to activate VisualStudio.
we do not have the product key and couldn't proceed further.  Please advise.

https://github.com/microsoft/MCW-Serverless-architecture/blob/main/Hands-on%20lab/HOL%20step-by-step%20-%20Serverless%20architecture.md

**Comment by sadukie** [comment]
You will not need a license key if you are using the lab VM for this Serverless MCW.  The ARM template is set to use Visual Studio Community Edition, not Enterprise Edition (as seen in your screenshot).  Once you have the Lab VM working for this MCW, you will notice the version like this:

![image](https://user-images.githubusercontent.com/106202/153217224-f2a328fb-00d1-469f-a704-33b4cd030249.png)

Once you have #113 resolved, that should resolve this issue here.

**Comment by PremalathaRajendran1** [comment]
@[sadukie]

You are right, we should fix the ARM Template first.
