### ISSUE TITLE
March 2019 - Scheduled content update

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [Microsoft/MCW-Serverless-architecture#31]
@ZoinerTejada @joelhulen @kylebunting
Solliance team -
This workshop is scheduled for an update in March. Please update this issue with suggested content changes. Once done, we'll assign to our SME team for review and additional feedback.

**Comment by joelhulen** [comment]
Here are my update suggestions:

- Update functions to v2
- Update functions to be triggered from Event Grid rather than blob storage. This will eliminate the delay of the function being triggered after an image is uploaded (wasn't available when created a year ago)

**Comment by givenscj** [comment]
Only thing I'd add is make the last part utilize Azure DevOps rather than GitHub.

**Comment by waltermyersiii** [comment]
I would be careful not to add too much complexity that would get away from the intent of the workshop. As much as I love Azure DevOps, if we're just using it as a repository, then what is the additional value add?

**Comment by dbarkol** [comment]
How about leveraging the API Management Consumption tier to expose a GET request that will query the Cosmos store? Perhaps apply some rate-limiting as well. A use case could be that folks might want to retrieve information about their vehicles and the captured images.

**Comment by soanain** [comment]
Perhaps extend this to functions on ASE. Rarely any of big accounts use standard web app as they want everything on network and go with ASE which changes a lot of things in architecture. But it may be complex initially. So can be added later in the assignment as an add on. Also to keep things simple, may be use azure SQL in place of cosmos as most the audience we get is already familiar with MSSQL and it may be easy for them to understand cloud version rather than explaining cosmos from scratch. May also give lot of incoming folks who are looking at end of life and idea of azure SQL.

**Comment by joelhulen** [comment]
@dbarkol That sounds like a good idea, especially since API Management now has the Consumption tier. If we include that in the lab (not sure if you're advocating that, or just the WDS), do you think it's necessary to go through the trouble to demonstrate the rate-limiting, or do you think just setting it up and explaining what it does is sufficient?

**Comment by joelhulen** [comment]
@soanain I agree with what you're saying. However, we try to avoid having an ASE in any labs, due to cost, the time it takes to provision, and other complexities. If you are advocating that for the lab, then we would need to justify its use case. For automated processing of images, I'm not sure it makes sense. If there are external users calling the functions directly, then we could work a story around it. As for Cosmos DB, that was requested by the original SMEs, Jeff Hollan included, due to it being a cloud-borne "serverless" database offering. I agree that SQL is more familiar to folks and is most often the right answer compared to Cosmos, but I also think that having Cosmos DB as part of the WDS and lab is a great way for people to become more familiar with it. Interested to hear what others think as well.

**Comment by givenscj** [comment]
I agree with Joel, ASE costs are still too high for these labs.  It makes sense for the security MCW, but in my opinion not for this one.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dbarkol** [comment]
@joelhulen , rate-limiting isn't necessary, good point. As long as they walk way with learning about the consumption tier, then it's a win.

**Comment by joelhulen** [comment]
@dbarkol Do you think this scenario with APIM should just be added to the WDS, or do you also think it should be added to the lab? Just thinking about overall time to complete the lab. Right now, it takes roughly four hours to complete, which is our target. Do you think it's worthwhile adding to the lab, given the number of extra steps that will be involved? Just curious if the trade-off of time is worth it, since we would also have to add a new HTTP-triggered function and figure out what it's supposed to do in the lab.

**Comment by dbarkol** [comment]
The lab is already very time-intensive. The WDS is a perfect showcase for it, so that should be more than enough.

**Comment by DawnmarieDesJardins** [comment]
@givenscj @joelhulen @ZoinerTejada 
Solliance team - Please move forward with the update with your recommendations and feedback given. Thanks!

**Comment by joelhulen** [comment]
@DawnmarieDesJardins I'll be working on this and will update this issue when I'm ready for a review.

**Comment by nikkiconley** [comment]
Task 4 : Provision the Azure Cosmos DB account 
The screen shots are out of date and the partition kay (required) is not in the instructions

**Comment by joelhulen** [comment]
@nikkiconley Thanks. That will be updated as well. The Cosmos DB UI moved away from offering a "Fixed" storage capacity where you did not need to specify a partition key. Now you do need to specify one, which is recommended anyway.

**Comment by joelhulen** [comment]
@DawnmarieDesJardins I've submitted a pull request that addresses the requested updates. Please let the SMEs know the changes are ready for review.

**Comment by nikkiconley** [comment]
When will the updates be posted?

**Comment by joelhulen** [comment]
@nikkiconley It should be any day. The changes are complete and they have been reviewed by SMEs. We're just waiting on the final QC (quality control) pass before the merge.

**Comment by DawnmarieDesJardins** [comment]
Hello!  Closing this issue with the recent update.
