### ISSUE TITLE
Uploadimage.exe file is missing 

### ISSUE THREAD

**Issue by Gvashi** [microsoft/MCW-Serverless-architecture#50]
Exercise 4:- Task 3 :- step 5
Showing an error , i.e file name "Uploadimage.exe" is missing.
I have attached  screenshot  for reference
![001](https://user-images.githubusercontent.com/53901647/66924037-8965b880-f047-11e9-8659-9b3765907b21.PNG)

**Comment by joelhulen** [comment]
Please follow the instructions in the before-the hands-on lab guide to extract the files to the proper location: <https://github.com/microsoft/MCW-Serverless-architecture/blob/master/Hands-on%20lab/Before%20the%20HOL%20-%20Serverless%20architecture.md#task-6-download-and-explore-the-tollbooth-starter-solution>

One issue you'll encounter is errors about file name length due to the number of embedded paths.

**Comment by joelhulen** [comment]
OK, I will look into it soon.

**Comment by joelhulen** [comment]
@Gvashi I have updated the code for the UploadImage project. Can you please download the latest version and try again?

**Comment by joelhulen** [comment]
@Gvashi, can you please verify everything works now? I will close this ticket in 24 hours if I've not heard back from you. Thanks.
