### ISSUE TITLE
HOL Exercise 5: Not able to see license plates data in Cosmos DB 

### ISSUE THREAD

**Issue by bala1074** [microsoft/MCW-Serverless-architecture#73]
Followed exact same steps mentioned on HOL: https://cloudworkshop.blob.core.windows.net/serverless-architecture/Hands-on%20lab/HOL%20step-by-step%20-%20Serverless%20architecture.html#serverless-architecture-hands-on-lab-step-by-**step

**Application Map**
![ws](https://user-images.githubusercontent.com/12669425/88092010-73c08900-cbad-11ea-9483-fc475c056528.png)

**Cosmos DB**
![cdb](https://user-images.githubusercontent.com/12669425/88092128-a074a080-cbad-11ea-8e10-9172f25325c8.png)

**Comment by joelhulen** [comment]
There are any number of reasons this could happen. Most often, it’s because someone missed a step or mis-typed the Event Grid topic filter name. Check everything you’ve had to type in as values, especially for the Azure resources. Make sure you;’ve completed the code steps. Double-check all the steps to make sure none were missed, especially when it comes to the Azure Functions and linked services like Cosmos DB and Event Grid subscriptions. Check the App Insights Live Metrics as the files are uploading to make sure there are no errors.

**Comment by joelhulen** [comment]
Were you able to figure this out?

**Comment by bala1074** [comment]
yes, CosmosDB IP changed to other, I added new cosmosDB IP to the firewall, It's working.
