### ISSUE TITLE
March 2021 update suggestions

### ISSUE THREAD

**Issue by kylebunting** [microsoft/MCW-Serverless-architecture#87]
I recommend the following updates. Please provide feedback on the following:

WDS
- Add discussion of durable functions and the premium tier of Azure Functions under the license plate processing using serverless components section of the preferred solution (question 3).
	- Also include a mention under the checklist of preferred objection handling (question 2).
- Change recommendation for storage to ADLS Gen2 versus Azure Blob storage, given the requirement for future advanced analytics workloads against license plate data?
- Add GitHub Actions to the WDS and architecture diagram.

HOL:
- Automate resource setup using an ARM template by taking the resource provisioning step currently in the before the hands-on lab document and any from the hands-on lab document and add them to an ARM template to automate resource setup.
- Update all images used in the lab to correspond with the latest portal UI changes
- Use ADLS Gen2 Storage account
- Update NuGet packages and SDKs to the latest versions

**Comment by DawnmarieDesJardins** [comment]
Feedback received via email:
Instead of Durable Functions, I would rather suggest to go little deeper on few scenarios. Examples:
1.	Some connectors in Logic Apps ( e.g. O365 ) and highlight how identity/authorization becomes so much more simpler in Logic Apps. 
2.	Functions – something on binding  
3.	Is there something we can add to highlight the changes we have done on cold start – as as objection handling. Expected talking points should be architecture changes in Functions 2.0 etc.

**Comment by DawnmarieDesJardins** [comment]
Additional email feedback:
I agree we should add mentioning the premium tier of Azure functions in the dialog for question 3 replacing App service.
 
As far as bindings, it looks like there is mention of two key bindings, Cosmos and Blob Storage. Mentioning of event grid binding could be added as well.
 
If we can fit in Durable Functions in the WDS and it feels natural it would be great to mention it as well. When it comes to durable/logic apps there are some overlap but it can be emphasized that depending on the experience and end user can dictate which one you use design first (Logic Apps) vs code first (Durable).

**Comment by DawnmarieDesJardins** [comment]
Closing issue with merge of PR #89
